[package]
name = "code_generation_rust"
version = "0.1.0"
authors = ["Warhorst <46809804+Warhorst@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "lib"}

[workspace]
members = [
    "lib"
]